name: neura_browser
description: A cross-platform private browser built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView for Android/iOS
  webview_flutter: ^4.4.1

  # WebView for Windows
  webview_windows: ^0.2.0

  # State management and local storage
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  local_auth: ^2.1.8
  flutter_html: ^3.0.0
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/adblock.js
